# Makefile.multi_reactor - 主从 Reactor 测试
# 用法: make -f Makefile.multi_reactor   （在 test_case/ 目录下执行）

.PHONY: all clean

CXX      = g++
CXXFLAGS = -Wall -g -m64 -fPIC -std=c++20 -fcoroutines -pthread -MMD -MP -include precompiled.h

INCLUDE  = -I./ -I..

LDFLAGS  = -L./ -L../../lib
LDLIBS   = -ldl -pthread

BIN_PATH = .
TARGET   = test_multi_reactor

TEST_SOURCES = test_multi_reactor.cc \
                ../Actor.cc \
                ../ActorSystem.cc \
                ../Timer.cc \
                ../EventLoop.cc \
                ../Epollor.cc \
                ../ConnectionBase.cc \
                ../Connection.cc \
                ../Acceptor.cc \
                ../Connector.cc \
                ../IOHelper.cc

OBJECT_PATH    = ../../Obj/MultiReactor
OBJECTS        = $(addprefix $(OBJECT_PATH)/,$(notdir $(TEST_SOURCES:.cc=.o)))
DEPS           = $(OBJECTS:.o=.d)

all: $(BIN_PATH)/$(TARGET)

$(BIN_PATH)/$(TARGET): $(OBJECTS)
	$(CXX) $(CXXFLAGS) $^ $(LDFLAGS) $(LDLIBS) -o $@

$(OBJECT_PATH)/%.o: %.cc | $(OBJECT_PATH)
	$(CXX) $(CXXFLAGS) -c $< $(INCLUDE) -o $@

$(OBJECT_PATH)/%.o: ../%.cc | $(OBJECT_PATH)
	$(CXX) $(CXXFLAGS) -c $< $(INCLUDE) -o $@

$(OBJECT_PATH):
	mkdir -p $(OBJECT_PATH)

-include $(DEPS)

clean:
	rm -rf $(OBJECT_PATH)/*.o $(OBJECT_PATH)/*.d $(BIN_PATH)/$(TARGET)
