# Makefile.multi_reactor_bench - 多 Reactor 完整压测套件
# 用法: make -f Makefile.multi_reactor_bench

.PHONY: all clean

CXX      = g++
CXXFLAGS = -O2 -Wall -m64 -fPIC -std=c++20 -fcoroutines -pthread -MMD -MP -include precompiled.h
# 注意：bench 用 -O2 比 -g 性能高一个数量级，更能反映真实极限

INCLUDE  = -I./

LDFLAGS  = -L./
LDLIBS   = -ldl -pthread

BIN_PATH = .
TARGET   = test_multi_reactor_bench

TEST_SOURCES = test_multi_reactor_bench.cc \
                Actor.cc \
                ActorSystem.cc \
                Timer.cc \
                EventLoop.cc \
                Epollor.cc \
                ConnectionBase.cc \
                Connection.cc \
                Acceptor.cc \
                Connector.cc \
                IOHelper.cc

OBJECT_PATH    = ../Obj/MultiReactorBench
OBJECTS        = $(patsubst %.cc,$(OBJECT_PATH)/%.o,$(TEST_SOURCES))
DEPS           = $(OBJECTS:.o=.d)

all: $(BIN_PATH)/$(TARGET)

$(BIN_PATH)/$(TARGET): $(OBJECTS)
	$(CXX) $(CXXFLAGS) $^ $(LDFLAGS) $(LDLIBS) -o $@

$(OBJECT_PATH)/%.o: %.cc | $(OBJECT_PATH)
	$(CXX) $(CXXFLAGS) -c $< $(INCLUDE) -o $@

$(OBJECT_PATH):
	mkdir -p $(OBJECT_PATH)

-include $(DEPS)

clean:
	rm -rf $(OBJECT_PATH)/*.o $(OBJECT_PATH)/*.d $(BIN_PATH)/$(TARGET)
