# Makefile.test - Actor???????????¨´??????
# ?¡Â?: make -f Makefile.test
#
# ???????????????EventLoop + Epollor + Connection + Acceptor + Connector??
# ??? Actor ?????Actor + ActorSystem??????? main.cc / TcpServer / TcpClient

.PHONY: all clean

CXX      = g++
CXXFLAGS = -Wall -g -m64 -fPIC -std=c++20 -pthread -MMD -MP -include precompiled.h

INCLUDE  = -I./

LDFLAGS  = -L./
LDLIBS   = -ldl -pthread

BIN_PATH = .
TARGET   = test_actor_msg

# ????????????????? main.cc / TcpServer.cc / TcpClient.cc??
TEST_SOURCES = test_actor_msg.cc \
               Actor.cc \
               ActorSystem.cc \
               Timer.cc \
               EventLoop.cc \
               Epollor.cc \
               ConnectionBase.cc \
               Connection.cc \
               Acceptor.cc \
               Connector.cc \
               IOHelper.cc

OBJECT_PATH    = ../Obj/NetTest
OBJECTS        = $(patsubst %.cc,$(OBJECT_PATH)/%.o,$(TEST_SOURCES))
DEPS           = $(OBJECTS:.o=.d)

all: $(BIN_PATH)/$(TARGET)

$(BIN_PATH)/$(TARGET): $(OBJECTS)
	$(CXX) $(CXXFLAGS) $^ $(LDFLAGS) $(LDLIBS) -o $@

$(OBJECT_PATH)/%.o: %.cc | $(OBJECT_PATH)
	$(CXX) $(CXXFLAGS) -c $< $(INCLUDE) -o $@

$(OBJECT_PATH):
	mkdir -p $(OBJECT_PATH)

-include $(DEPS)

clean:
	rm -rf $(OBJECT_PATH)/*.o $(OBJECT_PATH)/*.d $(BIN_PATH)/$(TARGET)
